### ISSUE TITLE
Voll schön

### ISSUE THREAD

**Issue by manuel-simon** [SFTtech/sticker#10]
Hi there, 
I would love to see a sticker stating "voll schön".
Best would be having a pink princess with a star magic wand and a violet unicorn on the picture. Last but not least, surrounding the whole picture with a chain of flowers would be awesome!

**Comment by mhcp6** [comment]
we are working on it

**Comment by nico5300** [comment]
pls upload it :)

**Comment by TheJJ** [comment]
Fixed in #12
