### ISSUE TITLE
Müdigkeit? Nein Danke

### ISSUE THREAD

**Issue by nikeee** [SFTtech/sticker#6]
Maybe you want to add this sticker:
http://threeheadedmonkey.soup.io/tag/club%20mate

Direct link:
https://asset-e.soup.io/asset/3774/1950_ef34.svg

Couldn't find anly license, except this:
> Name it, rate it, tune it, print it, Scan it, send it, fax - rename it, ...

**Comment by TheJJ** [comment]
Do you know the author? I assume you aren't the author yourself.

I'd rather not add stickers on behalf of non-authors, especially if the license is unclear :smiley:

**Comment by nikeee** [comment]
Well, I don't know the author. Good point. Closing this for now.
